services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    ports:
      - 32469:32469/tcp
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 3005:3005/tcp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ="America/Chicago"
      - PLEX_CLAIM="${PLEX_CLAIM_TOKEN}"
      - ADVERTISE_IP="http://${IP_ADDRESS}:32400/"
    volumes:
      - /nas/services/plex/config:/config
      - /nas/services/plex/transcode:/transcode
      - /nas/videos:/data

networks:
  default:
    name: main
    external: true
