services:
  gitea:
    container_name: gitea
    image: docker.gitea.com/gitea:1.25
    environment:
      USER_UID: 1000
      USER_GID: 1000
    restart: always
    volumes:
      - /nas/services/gitea/data:data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "127.0.0.1:2222:22"

networks:
  default:
    name: main
    external: true
